[package]
name = "zksync-revm"
version = "0.1.0"
edition = "2024"

[dependencies]
revm = { version = "=29.0.0", features = ["optional_balance_check"] }
auto_impl = "1.3.0"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_derive = "1.0"

